name: build-armbian
description: Build the host application for the specified OS and architecture

inputs:
    armbian_board:
        description: 'Armbian Board'
        required: true
        default: ''
    armbian_token:
        description: 'GitHub Token for release'
        required: false
        default: ''
    armbian_release:
        description: 'Armbian Release'
        required: true
        default: 'trixie'
    armbian_kernel_branch:
        description: 'Armbian Kernel Branch'
        required: true
        default: 'current'
    armbian_version:
        description: 'Armbian Version'
        required: false
        default: ''
    # armbian_extensions:
    #     description: 'Enable Armbian Extensions (yes/no)'
    #     required: true
    #     default: 'no'
    armbian_compress:
        description: 'Compress output image (yes/no)'
        required: true
        default: 'no'
    armbian_boot_scenario:
        description: 'Armbian Boot Scenario'
        required: false
        default: ''
    artifact_id:
        description: 'Output Image Artifact Identifier'
        required: true
    tezsign_flavour:
        description: 'TezSign flavour to build'
        required: false
        default: 'prod'

runs:
  using: "composite"
  steps:
    # - name: Free Github Runner
    #   uses: descriptinc/free-disk-space@main
    #   with:
    #     android: true
    #     dotnet: true
    #     haskell: true
    #     large-packages: true
    #     docker-images: true
    #     swap-storage: true

    - name: "Checkout Armbian os"
      uses: actions/checkout@v5
      with:
        repository: armbian/os
        fetch-depth: 0
        clean: false
        path: os

    - name: "Checkout Armbian build framework"
      uses: actions/checkout@v5
      with:
        repository: armbian/build
        ref: main
        clean: false
        path: build

    - name: "Prepare userpatches and version"
      shell: bash
      run: |
        # read version from upstream Armbian OS
        cat os/stable.json | jq '.version' | sed "s/\"//g" | sed 's/^/ARMBIAN_VERSION=/' >> $GITHUB_ENV
        [[ "${{ inputs.armbian_version }}" != '' ]] && echo "ARMBIAN_VERSION=${{ inputs.armbian_version }}" >> $GITHUB_ENV

        # copy os userpatches and custom
        mkdir -pv build/userpatches
        rsync -av os/userpatches/. build/userpatches/
        if [[ -d armbian_userpatches ]]; then
        rsync -av armbian_userpatches/. build/userpatches/
        fi

        # disable customize_image.sh in dev builds
        if [[ "${{ inputs.tezsign_flavour }}" == "dev" ]]; then
          rm -f build/userpatches/customize-image.sh
        fi

        # patch rpi bootsize in build/config/sources/families/bcm2711.conf to 128MB
        # declare -g UEFISIZE=512 -> declare -g UEFISIZE=128
        sed -i 's/declare -g UEFISIZE=[0-9]\+/declare -g UEFISIZE=128/' build/config/sources/families/bcm2711.conf

        # config/boards/radxa-zero3.csc comment out enable_extension "radxa-aic8800"
        # disables wifi/bluetooth driver
        sed -i '/enable_extension "radxa-aic8800"/ s/^/#/' build/config/boards/radxa-zero3.csc

    - shell: bash
      run: |

        # userspace decode
        BUILD_DESKTOP="no"
        BUILD_MINIMAL="yes"

        # go to build folder
        cd build

        # default build command below doesn't prepare host dependencies
        sudo ./compile.sh requirements
        sudo chown -R $USER:$USER .

        # execute build command
        ./compile.sh \
            REVISION="${{ env.ARMBIAN_VERSION }}" \
            BOARD="${{ inputs.armbian_board }}" \
            BRANCH="${{ inputs.armbian_kernel_branch }}" \
            RELEASE="${{ inputs.armbian_release }}" \
            KERNEL_CONFIGURE="no" \
            KERNEL_GIT=shallow \
            BUILD_DESKTOP="${BUILD_DESKTOP}" \
            BUILD_MINIMAL="${BUILD_MINIMAL}" \
            DESKTOP_ENVIRONMENT="${DESKTOP_ENVIRONMENT}" \
            DESKTOP_APPGROUPS_SELECTED="${DESKTOP_APPGROUPS_SELECTED}" \
            DESKTOP_ENVIRONMENT_CONFIG_NAME="${DESKTOP_ENVIRONMENT_CONFIG_NAME}" \
            COMPRESS_OUTPUTIMAGE="${{ inputs.armbian_compress }}" \
            BOOT_SCENARIO="${{ inputs.armbian_boot_scenario }}" \
            SHARE_LOG="yes" \
            NETWORKING_STACK=none \
            CONSOLE_AUTOLOGIN=false \
            FIXED_IMAGE_SIZE=${{ inputs.tezsign_flavour == 'dev' && 2000 || 1300 }} \
            ROOTFS_TYPE=ext4 \
            INCLUDE_HOME_DIR=false \
            EXTRA_ROOTFS_MIB_SIZE=128 \
            # ENABLE_EXTENSIONS=cleanup-packages \
            REMOVE_PACKAGES=alsa-utils,bash-completion,bc,bsdextrautils,command-not-found,cracklib-runtime,debconf-utils,debsums,dialog,evtest,f3,figlet,hdparm,htop,html2text,i2c-tools,iotop,jq,less,locales,logrotate,lsof,man-db,mc,ncurses-term,nano,pciutils,psmisc,pv,qrencode,readline-common,screen,smartmontools,stress,sysfsutils,toilet,toilet-fonts,unicode-data,unzip,usbutils,whiptail,xkb-data,avahi-autoipd,bluez,bluez-firmware,curl,ethtool,fping,iperf3,iputils-ping,iw,nfs-common,openssh-client,openssh-server,openssh-sftp-server,rfkill,rsync,systemd-resolved,vnstat,wget,wireguard-tools,wireless-regdb,wpasupplicant,apt-file,aptitude,armbian-config,cron,dkms,gpiod,libnss-myhostname,plymouth,plymouth-themes,rng-tools,unattended-upgrades,automake,bison,build-essential,expect,flex,git,gnupg2,libdigest-sha-perl,libnl-3-dev,libnl-genl-3-dev,libperl5.40,libproc-processtable-perl,libtirpc-common,libtirpc3t64,libwrap0-dev,libyaml-0-2,python3,btrfs-progs,device-tree-compiler,dosfstools,f2fs-tools,fbset,mmc-utils,mtd-utils,ntfs-3g \
            EXPERT="yes"

        mv output/images/*.img ../${{ inputs.artifact_id }}.img

    - uses: actions/upload-artifact@v5
      with:
        name: ${{ inputs.artifact_id }}
        path: ./${{ inputs.artifact_id }}.img
        retention-days: 1
        if-no-files-found: error